{
  inputs,
  pkgs,
  lib,
  ...
}: {
  # environment.shellInit = ''
  #   ulimit -n 2048
  #   '';

  homebrew = {
    enable = true;

    onActivation = {
      autoUpdate = true;
      cleanup = "zap";
      upgrade = true;
    };

    brewPrefix = "/opt/homebrew/bin";

    caskArgs = {
      # no_quarantine = true;
    };

    brews = [
      # "antidote"
      # "bandwhich"
      # "bat"
      # "berkeley-db@5"
      # "bottom"
      # "brotli"
      # "c-ares"
      # "ca-certificates"
      # "cairo"
      # "cowsay"
      # "croc"
      # "dbus"
      # "direnv"
      # "diskonaut"
      # "erlang"
      # "fontconfig"
      # "freetype"
      # "fzf"
      # "gdbm"
      # "gettext"
      # "giflib"
      # "git-delta"
      # "gleam"
      # "glib"
      # "gmp"
      # "gnu-sed"
      # "gnupg"
      # "gnutls"
      # "gping"
      # "graphite2"
      # "harfbuzz"
      # "helix"
      # "hoard"
      # "icu4c"
      # "jpeg-turbo"
      # "jq"
      # "lazydocker"
      # "lazygit"
      # "libassuan"
      # "libevent"
      # "libgcrypt"
      # "libgit2"
      # "libgpg-error"
      # "libidn2"
      # "libksba"
      # "libnghttp2"
      # "libpng"
      # "libsodium"
      # "libssh2"
      # "libtasn1"
      # "libtiff"
      # "libtool"
      # "libunistring"
      # "libusb"
      # "libuv"
      # "libvterm"
      # "libx11"
      # "libxau"
      # "libxcb"
      # "libxdmcp"
      # "libxext"
      # "libxrender"
      # "libyaml"
      # "little-cms2"
      # "llvm"
      # "lpeg"
      # "lsd"
      # "lua"
      # "luajit"
      # "luv"
      # "lz4"
      # "lzo"
      # "m4"
      # "mpdecimal"
      # "msgpack"
      # "ncurses"
      # "neofetch"
      # "neovim"
      # "nettle"
      # "nnn"
      # "node"
      # "npth"
      # "nushell"
      # "oha"
      # "oniguruma"
      # "openjdk"
      # "openjdk@17"
      # "openldap"
      # "openssl@1.1"
      # "openssl@3"
      # "p11-kit"
      # "pcre"
      # "pcre2"
      # "perl"
      # "pinentry"
      # "pixman"
      # "pnpm"
      # "portaudio"
      # "python@3.11"
      # "python@3.12"
      # "ranger"
      # "readline"
      # "rebar3"
      # "ripgrep"
      # "ruby"
      # "rustup-init"
      # "screenresolution"
      # "spotify-tui"
      # "spotifyd"
      # "sqlite"
      # "starship"
      # "tree-sitter"
      # "unbound"
      # "unibilium"
      # "unixodbc"
      # "vim"
      # "wasm-pack"
      # "wxwidgets"
      # "xh"
      # "xorgproto"
      # "xplr"
      # "xxh"
      # "xz"
      # "yazi"
      # "z3"
      # "zellij"
      # "zenith"
      # "zoxide"
      # "zsh"
      # "zstd"
    ];

    casks = [
      # "alacritty"
      # "beekeeper-studio"
      # "beeper"
      # "blender"
      # "caffeine"
      # "chromium"
      # "deluge"
      # "discord"
      # "firefox"
      # "font-agave-nerd-font"
      # "font-comic-shanns-mono-nerd-font"
      # "font-hurmit-nerd-font"
      # "font-iosevka"
      # "font-iosevka-nerd-font"
      # "font-iosevka-ss01"
      # "font-monofur-nerd-font"
      # "font-monoid-nerd-font"
      # "font-tinos-nerd-font"
      # "gimp"
      # "inkscape"
      # "karabiner-elements"
      # "krita"
      # "minecraft"
      # "nextcloud"
      # "podman-desktop"
      # "prismlauncher"
      # "protonvpn"
      # "rectangle"
      # "slack"
      # "spotify"
      # "steam"
      # "telegram-desktop"
      # "the-unarchiver"
      # "thunderbird"
      # "visual-studio-code"
      # "vlc"
    ];
  };

  environment.systemPackages = with pkgs; [
    alejandra
  ];

  services.nix-daemon.enable = lib.mkForce true;

  system.stateVersion = 4;
}
